config/routes.rb
Rails.application.routes.draw do
  
  get "home/index"
  resources :entities
  resources :groups
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  
    unauthenticated do
      root "home#index", as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :user

  validates :name, presence: true, length: { maximum: 255 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :entities, dependent: :destroy
  belongs_to :user
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 250 }

  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.includes(:groups).where(user_id: current_user.id).order(created_at: :desc)
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
    @categories = Group.where(user_id: current_user.id)
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    params = entity_params
    @entity = Entity.new(name: params[:name], amount: params[:amount])
    @entity.user_id = current_user.id
    @categories_ids = params[:group_ids]
    @categories_ids.each do |id|
      group = Group.find(id) unless id == ''
      @entity.groups.push(group) unless group.nil?
    end

    respond_to do |format|
      if @entity.save
        format.html { redirect_to groups_url(params[:group_id]), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to groups_url(params[:group_id]), notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:entities).where(user_id: current_user.id)
    @groups = Group.order(created_at: :desc)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>" class="shadow p-3 mb-3 bg-body-tertiary rounded">
  <%= link_to entity, class: "nav-link" do %>
    <div class="d-flex justify-content-between align-items-center">
      <p>
        <strong>Name:</strong>
        <%= entity.name %>
      </p>

      <p>
        <strong>Amount:</strong>
        $<%= entity.amount %>
      </p>
    </div>
<% end %>
  
</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
<header class="bg-primary text-white">
  <nav class="d-flex justify-content-between p-2 align-items-center text-reset">   
    <a href="<%= groups_path%>"><i class="fas fa-arrow-left fs-1 text-white"></i></a>
    <h2 class="m-0 p-0">New transaction</h2>
    <%= form.submit "Save", class: "nav-link fs-2" %>
  </nav> 
</header>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <%= form.text_field :name, placeholder: "Name", class: "form-control rounded-0" %>
  </div>

  <div>
    <%= form.number_field :amount, placeholder: "Enter number", class: "form-control rounded-0" %>
  </div>

  <div>
    <%= form.select :group_ids, @categories.collect {|cat| [cat.name, cat.id]}, { include_blank: false }, required: true, multiple: true, placeholder: "Select Categories", class: "form-control rounded-0" %>

  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<%= render "shared/transactionsnavbar" %>
<p style="color: green"><%= notice %></p>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
  <% end %>
</div>

<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center bg-success w-100 p-3">
  <%= link_to "Add a new Transaction", new_entity_path, class: "text-white w-100  nav-link border border-white  p-2" %>
</div>

app/views/entities/new.html.erb
<%= render "form", entity: @entity, categories: @categories %>

app/views/entities/show.html.erb
<header class="bg-primary text-white sticky-top">
  <nav class="d-flex justify-content-between p-3 align-items-center text-center">   
    <a href="<%= entities_path %>"><i class="fa-solid fa-arrow-left fs-1 text-white"></i></a>
    <h2 class="m-0 p-0">Transactions</h2>
    <i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
  </nav> 
</header>

<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div class="d-flex flex-column justify-content-between align-items-center p-3">
  <div>
    <%= button_to "Destroy this entity", @entity, method: :delete, class: "btn btn-link link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
  </div>
  
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
<header class="bg-primary text-white">
  <nav class="d-flex justify-content-between p-2 align-items-center text-reset">   
    <a href='/groups'><i class="fas fa-arrow-left fs-1 text-white"></i></a>
    <h2 class="m-0 p-0">New Category</h2>
    <%= form.submit "Save", class: "nav-link fs-2" %>
  </nav> 
</header>

  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <%= form.text_field :name, placeholder: "Name", class: "form-control rounded-0" %>
  </div>

  <div>
    <%= form.file_field :icon, placeholder: "Icon", class: "form-control rounded-0" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="shadow p-3 mb-3" id="<%= dom_id group %>">
  <%= link_to group_path(group), class: "d-flex align-items-center gap-4 w-full bg-white p-3 nav-link" do%>
  <% if group.icon.attached? %>
    <%= image_tag url_for(group.icon), class: "img-fluid img-thumbnail w-25" %>
    <% end %>
    <div class=" d-flex flex-column justify-content-between flex-fill">
      <div class="d-flex justify-content-between align-items-center w-full">
        <h3 class="fs-1 text-secondary "><%= group.name %></h3>
        <div class="fw-bold">
          $<%= group.entities.sum(:amount) %>
        </div>
      </div>
      <p class="opacity-25 align-self-start m-0"><%= group.created_at.strftime("%d %b %Y") %></p>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render "shared/categoriesnavbar" %>
<p style="color: green"><%= notice %></p>


<div id="groups">
  <% @groups.each do |group| %>
    <% if current_user.id == group.user_id %>
      <%= render group %>
    <% end %>
  <% end %>
</div>

<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center bg-success w-100 p-3">
  <%= link_to "Add a new category", new_group_path, class: "text-white w-100  nav-link border border-white  p-2" %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<header class="bg-primary text-white sticky-top">
  <nav class="d-flex justify-content-between p-3 align-items-center text-center">   
    <a href='/'><i class="fa-solid fa-arrow-left fs-1 text-white"></i></a>
    <h2 class="m-0 p-0">Transactions</h2>
    <i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
  </nav> 
</header>

<p style="color: green"><%= notice %></p>
<% if current_user.id == @group.user_id %>
  <div class="d-flex flex-column">
    <%= render @group %>
    <div class="mx-auto">
      <%= button_to "Remove category", @group, method: :delete, class: "btn btn-outline-primary"%>
    </div> 
  </div>
<% end %>

<h2 class="text-center mt-3">Transactions</h2>
<div class="">
  <% @group.entities.each do |entity| %>
  <% if current_user.id == entity.user_id %>
      <div class="d-flex flex-column shadow p-3 mb-5 bg-body-tertiary rounded">
        <div class="d-flex justify-content-between align-items-center">
          <h3><%= entity.name %></h3>
          <p>$<%= entity.amount %></p>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <span class="opacity-50"><%= entity.created_at.strftime("%d %b %Y") %></span>
          <%= button_to entity, method: :delete, class: "btn btn-link text-danger" do %>
          <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
        
      </div>
    <% end %>
  <% end %>
</div>

<div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center bg-success w-100 p-3">
  <%= link_to "Add a new Transaction", new_entity_path, class: "text-white w-100  nav-link border border-white  p-2" %>
</div>

app/views/home/index.html.erb
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 100vh;">
    <h1 class="fixed-center">
      Budget App
    </h1>

    <div class="d-flex flex-column fixed-bottom align-items-center justify-content-center text-center">
    <%= link_to "LOG IN", new_user_session_path, class: "text-white bg-primary w-100 p-3 nav-link" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link p-3 w-100" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/162dfb3961.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_categoriesnavbar.html.erb
<header class="bg-primary text-white sticky-top">
  <nav class="d-flex justify-content-between p-3 align-items-center text-center">   
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="fa-solid fa-bars fs-1 text-white"></span>
    </button>
    <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header d-flex align-items-center">
        <h3 class="m-0 p-0 align-self-center">Budget App</h3>
        <button type="button" class="btn-close btn-close-white " data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link fs-1" aria-current="page" href="<%= groups_path %>">Home</a>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-warning offcanvas-title mx-auto", id:"offcanvasDarkNavbarLabel" %>
          </li>
        </ul>
      </div>
    </div>
    <h2 class="m-0 p-0">Categories</h2>
    <i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
  </nav> 
</header>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

app/views/shared/_transactionsnavbar.html.erb
<header class="bg-primary text-white sticky-top">
  <nav class="d-flex justify-content-between p-3 align-items-center text-center">   
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="fa-solid fa-bars fs-1 text-white"></span>
    </button>
    <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header d-flex align-items-center">
        <h3 class="m-0 p-0 align-self-center">Budget App</h3>
        <button type="button" class="btn-close btn-close-white " data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link fs-1" aria-current="page" href="<%= groups_path %>">Home</a>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-warning offcanvas-title mx-auto", id:"offcanvasDarkNavbarLabel" %>
          </li>
        </ul>
      </div>
    </div>
    <h2 class="m-0 p-0">Categories</h2>
    <i class="fa-solid fa-magnifying-glass text-white fs-1"></i>
  </nav> 
</header>